# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tower Museum Shirt Factory Audio Guide
email: npetropoulos01@qub.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Tower Museum Audio Guide.
baseurl: "" # the subpath of your site, e.g. /blog
audio_path: "/audio/"
episode_hero_path: "/assets/img/stops/"
url: "https://kevinmeehanlyit.github.io/" # the base hostname & protocol for your site
logo: "/assets/img/logo/audio-guide.png"
twitter_username: N_Petropoulos
menu_heading: "Select another stop"
index_page_text: "<center>Welcome to the Tower Museum 'Shirt Factories of Derry/Londonderry' Exhibition. Select a number below to hear the amazing stories from the factory workers themselves.</center><br/>"
headphones_icon_color: "/assets/img/icons/headphones-dark.png"
headphones_icon_light: "/assets/img/icons/headphones-light.png"

# Build settings
markdown: kramdown

# Version settings (version number below is used for cache busting CSS and JS)
version_number: 1.0.0.1
